"""Synthetic-only tests for the private RLA-ES bundle builder.

The tests use invented dictionary, affix, notice, archive, and generated bytes.
They do not use Docker, the network, RLA-ES, CALLHOME, Bangor, ignored resources,
or private logs.
"""

from __future__ import annotations

import importlib.util
import io
import json
import stat
import sys
import zipfile
from pathlib import Path

import pytest

from cslm.utils.paths import project_root

_SCRIPT_PATH = project_root() / "scripts" / "build_spanish_rla_es_bundle.py"


def _load_script():
    spec = importlib.util.spec_from_file_location(
        "build_spanish_rla_es_bundle", _SCRIPT_PATH
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


runner = _load_script()

_SYNTHETIC_AFFIX = b"""SET UTF-8
FLAG UTF-8
PFX A Y 1
PFX A 0 syn .
SFX B Y 1
SFX B 0 z .
"""
_SYNTHETIC_DICTIONARY = b"""3
fakebase/A
invented/B
mockword/AB
"""


def _package_bytes(
    *,
    affix: bytes = _SYNTHETIC_AFFIX,
    dictionary: bytes = _SYNTHETIC_DICTIONARY,
    extra: bool = True,
) -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("es.dic", dictionary)
        archive.writestr("es.aff", affix)
        for name in runner.NOTICE_FILENAMES:
            archive.writestr(name, f"invented notice for {name}\n".encode())
        if extra:
            archive.writestr("META-INF/manifest.xml", b"invented metadata\n")
    return output.getvalue()


def _extraction(tmp_path: Path):
    return runner._extract_approved_members(_package_bytes(), tmp_path / "extracted")


def _safe_summary() -> dict[str, object]:
    return {
        "resource_release": runner.RESOURCE_RELEASE,
        "resource_source_commit": runner.RESOURCE_SOURCE_COMMIT,
        "selected_license_pathway": runner.SELECTED_LICENSE_PATHWAY,
        "source_download_runs": 2,
        "source_exact_byte_identity": True,
        "archive_safety_passed": True,
        "approved_extracted_member_count": 8,
        "unexpected_archive_member_count": 1,
        "notice_byte_preservation_passed": True,
        "affix_capability_supported": True,
        "unsupported_capability_count": 0,
        "generation_runs": 2,
        "generated_entry_count": 6,
        "generated_exact_byte_identity": True,
        "direct_hunspell_acceptance_passed": True,
        "bundle_entry_count": 11,
        "bundle_layout_passed": True,
        "git_ignored": True,
        "untracked": True,
        "unstaged": True,
        "atomic_promotion_passed": True,
        "no_corpus_access": True,
    }


def test_public_resource_and_environment_identities_are_pinned():
    assert runner.RESOURCE_RELEASE == "v2.9"
    assert runner.RESOURCE_SOURCE_COMMIT == "ea82c1214ead57740798acf66a1e18e5ac874c41"
    assert runner.RESOURCE_ASSET_ID == 217140315
    assert runner.RESOURCE_ASSET_SIZE == 1_475_270
    assert runner.SELECTED_LICENSE_PATHWAY == "MPL-1.1-or-later"
    assert runner.HUNSPELL_RELEASE == "v1.7.3"
    assert runner.HUNSPELL_COMMIT == "c5f98152a274e25b5107101104bef632b83a0cc9"
    assert runner.CONTAINER_PLATFORM == "linux/arm64"
    assert runner.CONTAINER_REFERENCE.startswith(
        "docker.io/library/buildpack-deps@sha256:"
    )


def test_exact_approved_filenames_and_counts():
    assert runner.EXTRACTED_FILENAMES == (
        "es.dic",
        "es.aff",
        "LICENSE.md",
        "GPLv3.txt",
        "LGPLv2.1.txt",
        "LGPLv3.txt",
        "MPL-1.1.txt",
        "README.txt",
    )
    assert len(runner.EXTRACTED_FILENAMES) == 8
    assert len(runner.NOTICE_FILENAMES) == 6
    assert len(runner.BUNDLE_FILENAMES) == 11
    assert len(set(runner.BUNDLE_FILENAMES)) == 11


def test_summary_schema_is_fixed_and_content_free():
    summary = _safe_summary()
    assert tuple(summary) == runner.SUMMARY_KEYS
    assert not any(key.endswith("_path") or "hash" in key for key in summary)


def test_live_identity_accepts_only_exact_public_metadata():
    release = {
        "tag_name": runner.RESOURCE_RELEASE,
        "assets": [
            {
                "id": runner.RESOURCE_ASSET_ID,
                "name": runner.RESOURCE_ASSET_NAME,
                "size": runner.RESOURCE_ASSET_SIZE,
                "content_type": runner.RESOURCE_ASSET_CONTENT_TYPE,
                "browser_download_url": runner.RESOURCE_ASSET_URL,
                "digest": "sha256:" + "a" * 64,
            }
        ],
    }
    tag_ref = {
        "object": {"type": "tag", "sha": runner.RESOURCE_TAG_OBJECT}
    }
    tag = {
        "sha": runner.RESOURCE_TAG_OBJECT,
        "object": {"type": "commit", "sha": runner.RESOURCE_SOURCE_COMMIT},
    }
    identity = runner._verify_live_identity(release, tag_ref, tag)
    assert identity.download_url == runner.RESOURCE_ASSET_URL
    assert identity.publisher_digest == "sha256:" + "a" * 64


@pytest.mark.parametrize(
    ("field", "bad_value"),
    [
        ("name", "invented.oxt"),
        ("size", 1),
        ("content_type", "application/zip"),
        ("browser_download_url", "https://example.invalid/invented"),
    ],
)
def test_live_identity_rejects_asset_metadata_drift(field, bad_value):
    asset = {
        "id": runner.RESOURCE_ASSET_ID,
        "name": runner.RESOURCE_ASSET_NAME,
        "size": runner.RESOURCE_ASSET_SIZE,
        "content_type": runner.RESOURCE_ASSET_CONTENT_TYPE,
        "browser_download_url": runner.RESOURCE_ASSET_URL,
    }
    asset[field] = bad_value
    release = {"tag_name": runner.RESOURCE_RELEASE, "assets": [asset]}
    tag_ref = {
        "object": {"type": "tag", "sha": runner.RESOURCE_TAG_OBJECT}
    }
    tag = {
        "sha": runner.RESOURCE_TAG_OBJECT,
        "object": {"type": "commit", "sha": runner.RESOURCE_SOURCE_COMMIT},
    }
    with pytest.raises(runner.BundleBuildError):
        runner._verify_live_identity(release, tag_ref, tag)


def test_safe_extraction_writes_only_allowlisted_members(tmp_path):
    extracted = _extraction(tmp_path)
    destination = tmp_path / "extracted"
    assert extracted.approved_member_count == 8
    assert extracted.unexpected_member_count == 1
    assert {path.name for path in destination.iterdir()} == set(
        runner.EXTRACTED_FILENAMES
    )
    assert all(path.is_file() and not path.is_symlink() for path in destination.iterdir())
    assert "META-INF/manifest.xml" not in extracted.files


def test_extraction_result_repr_omits_private_bytes(tmp_path):
    extracted = _extraction(tmp_path)
    rendered = repr(extracted)
    assert "fakebase" not in rendered
    assert "invented notice" not in rendered


def test_missing_required_member_fails_closed(tmp_path):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for name in runner.EXTRACTED_FILENAMES[1:]:
            archive.writestr(name, b"invented\n")
    with pytest.raises(runner.BundleBuildError) as excinfo:
        runner._extract_approved_members(output.getvalue(), tmp_path / "out")
    assert str(excinfo.value) == ""


def test_empty_required_notice_fails_closed(tmp_path):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for name in runner.EXTRACTED_FILENAMES:
            archive.writestr(name, b"" if name == "README.txt" else b"invented\n")
    with pytest.raises(runner.BundleBuildError):
        runner._extract_approved_members(output.getvalue(), tmp_path / "out")


def test_duplicate_archive_member_fails_closed(tmp_path):
    output = io.BytesIO()
    with pytest.warns(UserWarning, match="Duplicate name"):
        with zipfile.ZipFile(output, "w") as archive:
            for name in runner.EXTRACTED_FILENAMES:
                archive.writestr(name, b"invented\n")
            archive.writestr("es.dic", b"duplicate\n")
    with pytest.raises(runner.BundleBuildError):
        runner._extract_approved_members(output.getvalue(), tmp_path / "out")


@pytest.mark.parametrize("unsafe_name", ["../escape", "/absolute", "nested\\name"])
def test_unsafe_archive_path_fails_closed(tmp_path, unsafe_name):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for name in runner.EXTRACTED_FILENAMES:
            archive.writestr(name, b"invented\n")
        archive.writestr(unsafe_name, b"invented\n")
    with pytest.raises(runner.BundleBuildError):
        runner._extract_approved_members(output.getvalue(), tmp_path / "out")
    assert not (tmp_path / "escape").exists()


def test_archive_symlink_fails_closed(tmp_path):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w") as archive:
        for name in runner.EXTRACTED_FILENAMES:
            archive.writestr(name, b"invented\n")
        link = zipfile.ZipInfo("invented-link")
        link.create_system = 3
        link.external_attr = (stat.S_IFLNK | 0o777) << 16
        archive.writestr(link, b"invented-target")
    with pytest.raises(runner.BundleBuildError):
        runner._extract_approved_members(output.getvalue(), tmp_path / "out")


def test_supported_synthetic_dictionary_pair_is_content_free_in_repr():
    audit = runner._audit_dictionary_pair(_SYNTHETIC_DICTIONARY, _SYNTHETIC_AFFIX)
    assert audit.dictionary_entry_count == 3
    assert audit.affix_rule_count == 2
    assert audit.unsupported_capability_count == 0
    assert audit.flagged_query_words == audit.query_words
    assert "fakebase" not in repr(audit)
    assert "mockword" not in repr(audit)


def test_unflagged_base_is_not_sent_to_wordforms():
    dictionary = b"2\ninvented/A\nplainbase\n"
    audit = runner._audit_dictionary_pair(dictionary, _SYNTHETIC_AFFIX)
    assert audit.query_words == ("invented", "plainbase")
    assert audit.flagged_query_words == ("invented",)


def test_private_query_words_participate_in_audit_equality():
    first = runner._audit_dictionary_pair(
        b"1\ninvented/A\n", _SYNTHETIC_AFFIX
    )
    second = runner._audit_dictionary_pair(
        b"1\ndifferent/A\n", _SYNTHETIC_AFFIX
    )
    assert first != second


@pytest.mark.parametrize(
    "extra",
    [
        "COMPLEXPREFIXES\n",
        "COMPOUNDFLAG C\n",
        "ICONV 1\nICONV x y\n",
        "SFX C Y 1\nSFX C 0 z/D .\n",
        "UNREVIEWED invented\n",
    ],
)
def test_unreviewed_affix_capability_is_counted_without_content(extra):
    audit = runner._audit_dictionary_pair(
        _SYNTHETIC_DICTIONARY, _SYNTHETIC_AFFIX + extra.encode()
    )
    assert audit.unsupported_capability_count > 0
    assert extra.strip() not in repr(audit)


def test_dictionary_count_mismatch_fails_closed():
    with pytest.raises(runner.BundleBuildError):
        runner._audit_dictionary_pair(
            _SYNTHETIC_DICTIONARY.replace(b"3\n", b"4\n", 1),
            _SYNTHETIC_AFFIX,
        )


def test_regex_sensitive_query_is_an_unsupported_capability():
    dictionary = b"1\ninvented.word/A\n"
    audit = runner._audit_dictionary_pair(dictionary, _SYNTHETIC_AFFIX)
    assert audit.unsupported_capability_count == 1


def test_generated_list_validation_is_bytewise_and_strict():
    data = "alpha\námbito\n".encode()
    stats = runner._validate_generated_list(data)
    assert stats.entry_count == 2
    assert stats.byte_count == len(data)


@pytest.mark.parametrize(
    "data",
    [
        b"",
        b"invented",
        b"invented\r\n",
        b"invented\n\n",
        b" invented\n",
        b"two\none\n",
        b"same\nsame\n",
        b"bad\x00word\n",
        b"bad\xff\n",
    ],
)
def test_generated_list_malformed_bytes_fail_closed(data):
    with pytest.raises(runner.BundleBuildError):
        runner._validate_generated_list(data)


def test_docker_generation_is_offline_read_only_and_narrowly_mounted(
    tmp_path, monkeypatch
):
    fixture = tmp_path / "fixture"
    install = tmp_path / "install"
    output = tmp_path / "output"
    fixture.mkdir()
    install.mkdir()
    captured: list[str] = []

    def fake_run(command, *, timeout=900):
        captured.extend(command)
        return None

    monkeypatch.setattr(runner, "_run", fake_run)
    runner._run_generation(fixture, install, output)
    mounts = [captured[index + 1] for index, value in enumerate(captured) if value == "--mount"]
    assert captured[captured.index("--network") + 1] == "none"
    assert "--read-only" in captured
    assert captured[captured.index("--platform") + 1] == "linux/arm64"
    assert len(mounts) == 3
    assert any("dst=/fixture,readonly" in mount for mount in mounts)
    assert any("dst=/opt/hunspell,readonly" in mount for mount in mounts)
    assert any("dst=/output" in mount and "readonly" not in mount for mount in mounts)


def test_bundle_validation_requires_exact_regular_non_symlink_files(tmp_path):
    bundle = tmp_path / "bundle"
    bundle.mkdir()
    for name in runner.BUNDLE_FILENAMES:
        (bundle / name).write_bytes(b"invented\n")
    runner._validate_bundle(bundle)
    (bundle / "unexpected").write_bytes(b"invented\n")
    with pytest.raises(runner.BundleBuildError):
        runner._validate_bundle(bundle)


def test_atomic_promotion_refuses_existing_target(tmp_path):
    staging = tmp_path / "staging"
    target = tmp_path / "target"
    staging.mkdir()
    target.mkdir()
    with pytest.raises(runner.BundleBuildError):
        runner._atomic_promote(staging, target)


def test_assembled_bundle_promotes_as_one_exact_directory(tmp_path):
    extraction = _extraction(tmp_path)
    staging = tmp_path / "staging"
    staging.mkdir()
    runner._assemble_staging_bundle(
        staging,
        package=_package_bytes(),
        extraction=extraction,
        generated=b"invented\n",
        provenance={"invented": True},
    )
    target = tmp_path / "target"
    runner._atomic_promote(staging, target)
    assert not staging.exists()
    assert {path.name for path in target.iterdir()} == set(runner.BUNDLE_FILENAMES)
    assert len(tuple(target.iterdir())) == 11


def test_target_parent_preparation_refuses_symlink_component(tmp_path):
    root = tmp_path / "root"
    outside = tmp_path / "outside"
    root.mkdir()
    outside.mkdir()
    (root / "data").symlink_to(outside, target_is_directory=True)
    target = root / "data" / "resources" / "bundle"
    with pytest.raises(runner.BundleBuildError):
        runner._prepare_target_parent(root, target)


def test_deterministic_provenance_has_fixed_serialization(tmp_path):
    extraction = _extraction(tmp_path)
    identity = runner.LiveAssetIdentity(runner.RESOURCE_ASSET_URL, None)
    generated = "alpha\námbito\n".encode()
    stats = runner._validate_generated_list(generated)
    document = runner._build_provenance(
        runner_commit="1" * 40,
        identity=identity,
        downloads=(b"invented package", b"invented package"),
        extraction=extraction,
        generated_runs=(generated, generated),
        generated_stats=stats,
        unexpected_member_count=1,
    )
    first = runner._deterministic_json(document)
    second = runner._deterministic_json(document)
    assert first == second
    assert tuple(document) == runner.PROVENANCE_KEYS
    assert first.endswith(b"\n") and not first.endswith(b"\n\n")
    assert json.loads(first)["procedure_document_commit"] == runner.APPROVAL_DOCUMENT_COMMIT
    assert "personal" not in first.decode()


def test_cli_exposes_only_opt_in_and_help():
    parser = runner._build_parser()
    options: set[str] = set()
    for action in parser._actions:
        options.update(action.option_strings)
    assert options == {"-h", "--help", "--allow-rla-es-bundle-build"}


def test_default_refuses_before_execution(monkeypatch, capsys):
    def boom():
        raise AssertionError("execution must not be reached")

    monkeypatch.setattr(runner, "_execute", boom)
    assert runner.main([]) == runner.EXIT_OPT_IN_REQUIRED
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == runner._OPT_IN_MESSAGE + "\n"


def test_opt_in_prints_only_fixed_summary(monkeypatch, capsys):
    summary = _safe_summary()
    monkeypatch.setattr(runner, "_execute", lambda: summary)
    assert runner.main(["--allow-rla-es-bundle-build"]) == runner.EXIT_SUCCESS
    captured = capsys.readouterr()
    assert captured.err == ""
    assert list(json.loads(captured.out)) == list(runner.SUMMARY_KEYS)


def test_unsupported_capability_prints_only_aggregate_stop(monkeypatch, capsys):
    def stop():
        raise runner.UnsupportedCapabilityError(3)

    monkeypatch.setattr(runner, "_execute", stop)
    assert (
        runner.main(["--allow-rla-es-bundle-build"])
        == runner.EXIT_UNSUPPORTED_CAPABILITY
    )
    captured = capsys.readouterr()
    assert captured.out == ""
    assert json.loads(captured.err) == {
        "gate": "STOP",
        "unsupported_capability_count": 3,
        "bundle_promoted": False,
    }


def test_operational_failure_uses_fixed_non_sensitive_message(monkeypatch, capsys):
    def fail():
        raise RuntimeError("invented private path, hash, and word")

    monkeypatch.setattr(runner, "_execute", fail)
    assert (
        runner.main(["--allow-rla-es-bundle-build"])
        == runner.EXIT_OPERATIONAL_ABORT
    )
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == runner._ABORT_MESSAGE + "\n"
    assert "private path" not in captured.err


def test_keyboard_interrupt_uses_fixed_non_sensitive_message(monkeypatch, capsys):
    def interrupt():
        raise KeyboardInterrupt

    monkeypatch.setattr(runner, "_execute", interrupt)
    assert (
        runner.main(["--allow-rla-es-bundle-build"])
        == runner.EXIT_OPERATIONAL_ABORT
    )
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == runner._ABORT_MESSAGE + "\n"


@pytest.mark.parametrize("argument", ["--root", "--output", "--dictionary", "extra"])
def test_path_and_data_arguments_are_rejected(argument):
    with pytest.raises(SystemExit) as excinfo:
        runner.main([argument])
    assert excinfo.value.code == 2
