#!/usr/bin/env python
"""Run the synthetic-only Hunspell expansion feasibility gate.

This command uses only invented fixtures and public tool sources. It never
accepts a corpus path, dictionary path, resource path, output path, subset, or
language-data argument. The real RLA-ES bundle, CALLHOME, and Bangor are outside
its interface and remain closed.

The command refuses by default. With the explicit opt-in it:

* downloads the official Hunspell 1.7.3 source archive and verifies the public
  digest reported by GitHub;
* compiles that source with networking disabled inside one platform-and-digest
  pinned ARM64 container;
* validates a small, invented Hunspell fixture before invoking upstream tools;
* runs ``wordforms`` serially in two separate, read-only, network-disabled
  containers, each with a private ``/tmp``;
* compares both generated byte streams with each other and with a fixed expected
  synthetic set;
* checks the same bounded universe with the pinned Hunspell executable; and
* prints one content-free JSON object containing public identities, aggregate
  counts, and Boolean gate results.

No lexical entry, generated form, source hash, local path, build log, or tool
diagnostic is printed. All working files are temporary and deleted on exit.
This is a feasibility harness, not the later RLA-ES generation driver.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path, PurePosixPath

EXIT_SUCCESS = 0
EXIT_OPT_IN_REQUIRED = 2
EXIT_OPERATIONAL_ABORT = 3

_OPT_IN_MESSAGE = (
    "Refusing to run: pass --allow-synthetic-hunspell-run to execute the "
    "invented-fixture feasibility gate. Nothing was read or written."
)
_ABORT_MESSAGE = (
    "Synthetic feasibility run aborted. No resource or corpus was accessed, "
    "and no result bundle was produced."
)

HUNSPELL_RELEASE = "v1.7.3"
HUNSPELL_COMMIT = "c5f98152a274e25b5107101104bef632b83a0cc9"
HUNSPELL_ARCHIVE_NAME = "hunspell-1.7.3.tar.gz"
HUNSPELL_ARCHIVE_URL = (
    "https://github.com/hunspell/hunspell/releases/download/"
    f"{HUNSPELL_RELEASE}/{HUNSPELL_ARCHIVE_NAME}"
)
# Public digest returned by GitHub for release asset 412478719.
HUNSPELL_ARCHIVE_SHA256 = "433274dac0619cb00c2e18b43a3dd3a9d50da5b5613fa9b5c21781e35dd76bc1"

CONTAINER_REPOSITORY = "docker.io/library/buildpack-deps"
CONTAINER_TAG = "bookworm"
CONTAINER_INDEX_DIGEST = "sha256:5bfacbc6611775f980cf283fbc86b999517878d39723510687135a0d6366bbee"
CONTAINER_PLATFORM_DIGEST = (
    "sha256:a60c415ba968e9accc8795332295eca29c58968ef95d45616e90e2a5da40f498"
)
CONTAINER_PLATFORM = "linux/arm64"
CONTAINER_REFERENCE = f"{CONTAINER_REPOSITORY}@{CONTAINER_PLATFORM_DIGEST}"

_AFFIX_TEXT = """SET UTF-8
FLAG UTF-8
PFX A Y 1
PFX A 0 za .
SFX B Y 1
SFX B 0 in .
SFX C N 1
SFX C a o a
SFX D N 1
SFX D 0 z [ae]
"""

_DICTIONARY_TEXT = """6
synnulo
synpavor/A
synbrena/B
syncalum/AB
synnexa/C
synmire/D
"""

_EXPECTED_FORMS: tuple[str, ...] = (
    "synbrena",
    "synbrenain",
    "syncalum",
    "syncalumin",
    "synmire",
    "synmirez",
    "synnexa",
    "synnexo",
    "synnulo",
    "synpavor",
    "zasyncalum",
    "zasyncalumin",
    "zasynpavor",
)
_REJECTED_FORMS: tuple[str, ...] = ("synqorvax",)
_SCALE_BASE_COUNT = 1024

_FIXTURE_FILENAMES = frozenset(
    {
        "synthetic.aff",
        "synthetic.dic",
        "expected.txt",
        "candidates.txt",
        "rejected.txt",
        "run_generation.sh",
    }
)
_SAFE_WORD_RE = re.compile(r"[a-z]+")
_SAFE_ENTRY_RE = re.compile(r"(?P<word>[a-z]+)(?:/(?P<flags>[A-Z]+))?")

_EXPECTED_ENVIRONMENT = {
    "architecture": "aarch64",
    "os": "debian:12",
    "bash": "5.2.15(1)-release",
    "grep": "3.8",
    "awk": "1.3.4",
    "sort": "9.1",
    "locale": "UTF-8",
    "gcc": "12.2.0",
    "gxx": "12.2.0",
    "make": "4.3",
    "hunspell": "1.7.3",
    "wordforms_installed": "true",
}

SUMMARY_KEYS: tuple[str, ...] = (
    "hunspell_release",
    "hunspell_commit",
    "container_platform",
    "environment_identity_match",
    "offline_build",
    "synthetic_generation_runs",
    "generated_entry_count",
    "two_runs_byte_identical",
    "expected_set_match",
    "direct_hunspell_parity",
    "rejected_form_rejected",
    "scale_probe_base_count",
    "scale_probe_generated_entry_count",
    "scale_probe_two_runs_byte_identical",
    "scale_probe_expected_set_match",
    "scale_probe_direct_hunspell_parity",
    "missing_affix_failed_closed",
    "missing_dictionary_failed_closed",
    "malformed_affix_failed_closed",
    "malformed_dictionary_failed_closed",
    "unsupported_flag_mode_failed_closed",
    "unsupported_directive_failed_closed",
    "no_real_resource_or_corpus_access",
)


class SyntheticFeasibilityError(RuntimeError):
    """Any fail-closed synthetic environment or fixture failure."""


def _fixed_lines(path: Path) -> list[str]:
    """Read a strict UTF-8/LF text file without returning path-bearing errors."""
    if path.is_symlink() or not path.is_file():
        raise SyntheticFeasibilityError
    try:
        data = path.read_bytes()
        text = data.decode("utf-8", errors="strict")
    except (OSError, UnicodeError):
        raise SyntheticFeasibilityError from None
    if not data or not data.endswith(b"\n") or b"\r" in data or b"\x00" in data:
        raise SyntheticFeasibilityError
    lines = text.splitlines()
    if not lines or any(not line or line != line.strip() for line in lines):
        raise SyntheticFeasibilityError
    return lines


def _parse_affix(path: Path) -> frozenset[str]:
    """Validate the deliberately narrow invented affix fixture.

    This is not an RLA-ES parser. It recognizes only the small PFX/SFX subset
    needed by this synthetic proof and rejects every unreviewed directive or
    flag mode rather than silently ignoring it.
    """
    lines = _fixed_lines(path)
    if lines[:2] != ["SET UTF-8", "FLAG UTF-8"]:
        raise SyntheticFeasibilityError

    headers: dict[tuple[str, str], tuple[str, int]] = {}
    observed_rules: dict[tuple[str, str], int] = {}
    for line in lines[2:]:
        parts = line.split()
        if not parts or parts[0] not in {"PFX", "SFX"}:
            raise SyntheticFeasibilityError
        if len(parts) == 4 and parts[2] in {"Y", "N"} and parts[3].isdigit():
            kind, flag = parts[:2]
            if not re.fullmatch(r"[A-Z]", flag):
                raise SyntheticFeasibilityError
            key = (kind, flag)
            if key in headers:
                raise SyntheticFeasibilityError
            headers[key] = (parts[2], int(parts[3]))
            observed_rules[key] = 0
            continue
        if len(parts) != 5:
            raise SyntheticFeasibilityError
        kind, flag, strip, add, condition = parts
        key = (kind, flag)
        if key not in headers:
            raise SyntheticFeasibilityError
        tokens = (strip, add, condition)
        if not all(
            token and not any(char.isspace() for char in token) for token in tokens
        ):
            raise SyntheticFeasibilityError
        observed_rules[key] += 1

    if not headers:
        raise SyntheticFeasibilityError
    for key, (_, expected_count) in headers.items():
        if observed_rules[key] != expected_count:
            raise SyntheticFeasibilityError
    flags = [flag for _, flag in headers]
    if len(flags) != len(set(flags)):
        raise SyntheticFeasibilityError
    return frozenset(flags)


def _parse_dictionary(path: Path, *, allowed_flags: frozenset[str]) -> tuple[str, ...]:
    lines = _fixed_lines(path)
    if not lines[0].isdigit():
        raise SyntheticFeasibilityError
    entries = lines[1:]
    if int(lines[0]) != len(entries) or not entries:
        raise SyntheticFeasibilityError

    words: list[str] = []
    for entry in entries:
        match = _SAFE_ENTRY_RE.fullmatch(entry)
        if match is None:
            raise SyntheticFeasibilityError
        word = match.group("word")
        flags = match.group("flags") or ""
        if len(flags) != len(set(flags)) or not set(flags) <= allowed_flags:
            raise SyntheticFeasibilityError
        words.append(word)
    if len(words) != len(set(words)):
        raise SyntheticFeasibilityError
    return tuple(words)


def _validate_word_list(path: Path) -> tuple[str, ...]:
    lines = _fixed_lines(path)
    if any(_SAFE_WORD_RE.fullmatch(line) is None for line in lines):
        raise SyntheticFeasibilityError
    if lines != sorted(set(lines)):
        raise SyntheticFeasibilityError
    return tuple(lines)


def _validate_fixture_dir(fixture_dir: Path) -> None:
    if fixture_dir.is_symlink() or not fixture_dir.is_dir():
        raise SyntheticFeasibilityError
    try:
        present = {entry.name for entry in fixture_dir.iterdir()}
    except OSError:
        raise SyntheticFeasibilityError from None
    if present != _FIXTURE_FILENAMES:
        raise SyntheticFeasibilityError
    if any(entry.is_symlink() or not entry.is_file() for entry in fixture_dir.iterdir()):
        raise SyntheticFeasibilityError

    allowed_flags = _parse_affix(fixture_dir / "synthetic.aff")
    dictionary_words = _parse_dictionary(
        fixture_dir / "synthetic.dic", allowed_flags=allowed_flags
    )
    expected = _validate_word_list(fixture_dir / "expected.txt")
    candidates = _validate_word_list(fixture_dir / "candidates.txt")
    rejected = _validate_word_list(fixture_dir / "rejected.txt")
    if not set(dictionary_words) <= set(expected):
        raise SyntheticFeasibilityError
    if set(candidates) != set(expected) | set(rejected):
        raise SyntheticFeasibilityError
    if set(expected) & set(rejected):
        raise SyntheticFeasibilityError


_GENERATION_SCRIPT = """#!/usr/bin/env bash
set -euo pipefail
export PATH=/opt/hunspell/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LD_LIBRARY_PATH=/opt/hunspell/lib
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
cd /fixture
test -f synthetic.aff
test -f synthetic.dic
test -f candidates.txt
test -f rejected.txt

tail -n +2 synthetic.dic | while IFS= read -r entry; do
    word=${entry%%/*}
    printf '%s\n' "$word"
    case "$entry" in
        */*) wordforms synthetic.aff synthetic.dic "$word" ;;
    esac
done > /tmp/generated.unsorted
LC_ALL=C sort -u /tmp/generated.unsorted > /output/generated.txt
hunspell -d /fixture/synthetic -G -l < candidates.txt \
    | LC_ALL=C sort -u > /output/accepted.txt
hunspell -d /fixture/synthetic -l < rejected.txt > /output/rejected.txt
"""


def _write_fixture(fixture_dir: Path) -> None:
    fixture_dir.mkdir()
    expected_text = "".join(f"{word}\n" for word in _EXPECTED_FORMS)
    candidate_text = "".join(
        f"{word}\n" for word in sorted(_EXPECTED_FORMS + _REJECTED_FORMS)
    )
    rejected_text = "".join(f"{word}\n" for word in _REJECTED_FORMS)
    files = {
        "synthetic.aff": _AFFIX_TEXT,
        "synthetic.dic": _DICTIONARY_TEXT,
        "expected.txt": expected_text,
        "candidates.txt": candidate_text,
        "rejected.txt": rejected_text,
        "run_generation.sh": _GENERATION_SCRIPT,
    }
    for name, text in files.items():
        (fixture_dir / name).write_text(text, encoding="utf-8", newline="\n")
    (fixture_dir / "run_generation.sh").chmod(0o755)
    _validate_fixture_dir(fixture_dir)


def _alphabetic_id(index: int, *, width: int = 3) -> str:
    """Return a fixed-width lowercase identifier for invented scale entries."""
    if isinstance(index, bool) or type(index) is not int or not 0 <= index < 26**width:
        raise SyntheticFeasibilityError
    chars = ["a"] * width
    remaining = index
    for position in range(width - 1, -1, -1):
        remaining, digit = divmod(remaining, 26)
        chars[position] = chr(ord("a") + digit)
    return "".join(chars)


def _write_scale_fixture(fixture_dir: Path) -> None:
    """Create a bounded invented dictionary for repeated wordforms execution."""
    fixture_dir.mkdir()
    bases = tuple(
        f"synscale{_alphabetic_id(index)}" for index in range(_SCALE_BASE_COUNT)
    )
    expected = tuple(sorted((*bases, *(f"{word}x" for word in bases))))
    rejected = ("synscalezzzz",)
    candidates = tuple(sorted((*expected, *rejected)))
    dictionary = f"{len(bases)}\n" + "".join(f"{word}/A\n" for word in bases)
    affix = "SET UTF-8\nFLAG UTF-8\nSFX A Y 1\nSFX A 0 x .\n"
    files = {
        "synthetic.aff": affix,
        "synthetic.dic": dictionary,
        "expected.txt": "".join(f"{word}\n" for word in expected),
        "candidates.txt": "".join(f"{word}\n" for word in candidates),
        "rejected.txt": "".join(f"{word}\n" for word in rejected),
        "run_generation.sh": _GENERATION_SCRIPT,
    }
    for name, text in files.items():
        (fixture_dir / name).write_text(text, encoding="utf-8", newline="\n")
    (fixture_dir / "run_generation.sh").chmod(0o755)
    _validate_fixture_dir(fixture_dir)


def _run(command: list[str], *, timeout: int = 300) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (OSError, subprocess.SubprocessError):
        raise SyntheticFeasibilityError from None


def _download_source(archive_path: Path) -> None:
    try:
        with urllib.request.urlopen(HUNSPELL_ARCHIVE_URL, timeout=60) as response:
            data = response.read()
    except (OSError, TimeoutError):
        raise SyntheticFeasibilityError from None
    if hashlib.sha256(data).hexdigest() != HUNSPELL_ARCHIVE_SHA256:
        raise SyntheticFeasibilityError
    archive_path.write_bytes(data)


def _extract_source(archive_path: Path, destination: Path) -> Path:
    try:
        with tarfile.open(archive_path, "r:gz") as archive:
            members = archive.getmembers()
            for member in members:
                relative = PurePosixPath(member.name)
                if relative.is_absolute() or ".." in relative.parts:
                    raise SyntheticFeasibilityError
                if not (member.isdir() or member.isfile()):
                    raise SyntheticFeasibilityError
            archive.extractall(destination, members=members, filter="data")
    except (OSError, tarfile.TarError):
        raise SyntheticFeasibilityError from None
    source_dir = destination / "hunspell-1.7.3"
    if source_dir.is_symlink() or not source_dir.is_dir():
        raise SyntheticFeasibilityError
    if not (source_dir / "configure").is_file():
        raise SyntheticFeasibilityError
    if not (source_dir / "src" / "tools" / "wordforms").is_file():
        raise SyntheticFeasibilityError
    return source_dir


def _base_docker_args() -> list[str]:
    return [
        "docker",
        "run",
        "--rm",
        "--network",
        "none",
        "--platform",
        CONTAINER_PLATFORM,
        "--read-only",
        "--cap-drop",
        "ALL",
        "--security-opt",
        "no-new-privileges",
        "--tmpfs",
        "/tmp:rw,nosuid,nodev,noexec,size=64m",
        "-e",
        "LANG=C.UTF-8",
        "-e",
        "LC_ALL=C.UTF-8",
    ]


def _build_hunspell(source_dir: Path, install_dir: Path) -> None:
    install_dir.mkdir()
    _run(["docker", "pull", "--platform", CONTAINER_PLATFORM, CONTAINER_REFERENCE])
    command = _base_docker_args() + [
        "--mount",
        f"type=bind,src={source_dir},dst=/src",
        "--mount",
        f"type=bind,src={install_dir},dst=/install",
        "-w",
        "/src",
        CONTAINER_REFERENCE,
        "bash",
        "-lc",
        "./configure --prefix=/install >/tmp/configure.log 2>&1 "
        "&& make -j2 >/tmp/make.log 2>&1 "
        "&& make install >/tmp/install.log 2>&1 "
        "&& test -x /install/bin/hunspell "
        "&& test -x /install/bin/wordforms",
    ]
    _run(command)


def _inspect_environment(install_dir: Path) -> dict[str, str]:
    script = r"""
set -euo pipefail
export PATH=/opt/hunspell/bin:$PATH
export LD_LIBRARY_PATH=/opt/hunspell/lib
. /etc/os-release
printf 'architecture=%s\n' "$(uname -m)"
printf 'os=%s:%s\n' "$ID" "$VERSION_ID"
printf 'bash=%s\n' "$BASH_VERSION"
printf 'grep=%s\n' "$(grep --version | head -n1 | awk '{print $NF}')"
printf 'awk=%s\n' "$(awk -W version 2>&1 | head -n1 | awk '{print $2}')"
printf 'sort=%s\n' "$(sort --version | head -n1 | awk '{print $NF}')"
printf 'locale=%s\n' "$(locale charmap)"
printf 'gcc=%s\n' "$(gcc -dumpfullversion)"
printf 'gxx=%s\n' "$(g++ -dumpfullversion)"
printf 'make=%s\n' "$(make --version | head -n1 | awk '{print $3}')"
hunspell_version="$(hunspell --version | head -n1 \
    | sed -n 's/.*Hunspell \([0-9.]*\)).*/\1/p')"
printf 'hunspell=%s\n' "$hunspell_version"
test -x /opt/hunspell/bin/wordforms
printf 'wordforms_installed=true\n'
"""
    command = _base_docker_args() + [
        "--mount",
        f"type=bind,src={install_dir},dst=/opt/hunspell,readonly",
        CONTAINER_REFERENCE,
        "bash",
        "-lc",
        script,
    ]
    result = _run(command)
    observed: dict[str, str] = {}
    for line in result.stdout.splitlines():
        if "=" not in line:
            raise SyntheticFeasibilityError
        key, value = line.split("=", 1)
        if key in observed or not key or not value:
            raise SyntheticFeasibilityError
        observed[key] = value
    if observed != _EXPECTED_ENVIRONMENT:
        raise SyntheticFeasibilityError
    return observed


def _run_generation(fixture_dir: Path, install_dir: Path, output_dir: Path) -> None:
    output_dir.mkdir()
    command = _base_docker_args() + [
        "--mount",
        f"type=bind,src={fixture_dir},dst=/fixture,readonly",
        "--mount",
        f"type=bind,src={install_dir},dst=/opt/hunspell,readonly",
        "--mount",
        f"type=bind,src={output_dir},dst=/output",
        "-w",
        "/fixture",
        CONTAINER_REFERENCE,
        "bash",
        "/fixture/run_generation.sh",
    ]
    _run(command)


def _expect_closed_failure(operation) -> bool:
    try:
        operation()
    except SyntheticFeasibilityError:
        return True
    return False


def _exercise_fixture_failures(root: Path, fixture_dir: Path) -> dict[str, bool]:
    results: dict[str, bool] = {}

    def variant(name: str) -> Path:
        target = root / name
        shutil.copytree(fixture_dir, target)
        return target

    missing_aff = variant("missing_aff")
    (missing_aff / "synthetic.aff").unlink()
    results["missing_affix_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(missing_aff)
    )

    missing_dic = variant("missing_dic")
    (missing_dic / "synthetic.dic").unlink()
    results["missing_dictionary_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(missing_dic)
    )

    malformed_aff = variant("malformed_aff")
    (malformed_aff / "synthetic.aff").write_text(
        _AFFIX_TEXT.replace("PFX A Y 1", "PFX A Y 2"), encoding="utf-8", newline="\n"
    )
    results["malformed_affix_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(malformed_aff)
    )

    malformed_dic = variant("malformed_dic")
    (malformed_dic / "synthetic.dic").write_text(
        _DICTIONARY_TEXT.replace("6\n", "7\n", 1), encoding="utf-8", newline="\n"
    )
    results["malformed_dictionary_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(malformed_dic)
    )

    unsupported_flag = variant("unsupported_flag")
    (unsupported_flag / "synthetic.aff").write_text(
        _AFFIX_TEXT.replace("FLAG UTF-8", "FLAG long"), encoding="utf-8", newline="\n"
    )
    results["unsupported_flag_mode_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(unsupported_flag)
    )

    unsupported_directive = variant("unsupported_directive")
    (unsupported_directive / "synthetic.aff").write_text(
        _AFFIX_TEXT + "COMPLEXPREFIXES\n", encoding="utf-8", newline="\n"
    )
    results["unsupported_directive_failed_closed"] = _expect_closed_failure(
        lambda: _validate_fixture_dir(unsupported_directive)
    )
    if not all(results.values()):
        raise SyntheticFeasibilityError
    return results


def _read_output(path: Path) -> bytes:
    if path.is_symlink() or not path.is_file():
        raise SyntheticFeasibilityError
    try:
        data = path.read_bytes()
    except OSError:
        raise SyntheticFeasibilityError from None
    if not data or not data.endswith(b"\n") or b"\r" in data or b"\x00" in data:
        raise SyntheticFeasibilityError
    return data


def _execute() -> dict[str, object]:
    with tempfile.TemporaryDirectory(prefix="neu-lab-hunspell-synthetic-") as raw_root:
        root = Path(raw_root)
        archive_path = root / HUNSPELL_ARCHIVE_NAME
        _download_source(archive_path)
        source_dir = _extract_source(archive_path, root / "source")

        fixture_dir = root / "fixture"
        _write_fixture(fixture_dir)
        failure_results = _exercise_fixture_failures(root, fixture_dir)

        install_dir = root / "install"
        _build_hunspell(source_dir, install_dir)
        _inspect_environment(install_dir)

        run_one = root / "run_one"
        run_two = root / "run_two"
        _run_generation(fixture_dir, install_dir, run_one)
        _run_generation(fixture_dir, install_dir, run_two)

        expected = (fixture_dir / "expected.txt").read_bytes()
        rejected = (fixture_dir / "rejected.txt").read_bytes()
        generated_one = _read_output(run_one / "generated.txt")
        generated_two = _read_output(run_two / "generated.txt")
        accepted_one = _read_output(run_one / "accepted.txt")
        accepted_two = _read_output(run_two / "accepted.txt")
        rejected_one = _read_output(run_one / "rejected.txt")
        rejected_two = _read_output(run_two / "rejected.txt")

        two_runs_identical = generated_one == generated_two
        expected_match = generated_one == expected
        direct_parity = accepted_one == expected and accepted_two == expected
        rejected_match = rejected_one == rejected and rejected_two == rejected
        if not all((two_runs_identical, expected_match, direct_parity, rejected_match)):
            raise SyntheticFeasibilityError

        scale_fixture = root / "scale_fixture"
        _write_scale_fixture(scale_fixture)
        scale_run_one = root / "scale_run_one"
        scale_run_two = root / "scale_run_two"
        _run_generation(scale_fixture, install_dir, scale_run_one)
        _run_generation(scale_fixture, install_dir, scale_run_two)
        scale_expected = (scale_fixture / "expected.txt").read_bytes()
        scale_generated_one = _read_output(scale_run_one / "generated.txt")
        scale_generated_two = _read_output(scale_run_two / "generated.txt")
        scale_accepted_one = _read_output(scale_run_one / "accepted.txt")
        scale_accepted_two = _read_output(scale_run_two / "accepted.txt")
        scale_identical = scale_generated_one == scale_generated_two
        scale_expected_match = scale_generated_one == scale_expected
        scale_parity = (
            scale_accepted_one == scale_expected and scale_accepted_two == scale_expected
        )
        if not all((scale_identical, scale_expected_match, scale_parity)):
            raise SyntheticFeasibilityError

        summary: dict[str, object] = {
            "hunspell_release": HUNSPELL_RELEASE,
            "hunspell_commit": HUNSPELL_COMMIT,
            "container_platform": CONTAINER_PLATFORM,
            "environment_identity_match": True,
            "offline_build": True,
            "synthetic_generation_runs": 2,
            "generated_entry_count": len(_EXPECTED_FORMS),
            "two_runs_byte_identical": True,
            "expected_set_match": True,
            "direct_hunspell_parity": True,
            "rejected_form_rejected": True,
            "scale_probe_base_count": _SCALE_BASE_COUNT,
            "scale_probe_generated_entry_count": _SCALE_BASE_COUNT * 2,
            "scale_probe_two_runs_byte_identical": True,
            "scale_probe_expected_set_match": True,
            "scale_probe_direct_hunspell_parity": True,
            **failure_results,
            "no_real_resource_or_corpus_access": True,
        }
        if tuple(summary) != SUMMARY_KEYS:
            raise SyntheticFeasibilityError
        return summary


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the invented-fixture Hunspell feasibility gate."
    )
    parser.add_argument(
        "--allow-synthetic-hunspell-run",
        action="store_true",
        help="explicitly allow the temporary public-source and invented-fixture run",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if not args.allow_synthetic_hunspell_run:
        print(_OPT_IN_MESSAGE, file=sys.stderr)
        return EXIT_OPT_IN_REQUIRED
    try:
        summary = _execute()
    except Exception:
        print(_ABORT_MESSAGE, file=sys.stderr)
        return EXIT_OPERATIONAL_ABORT
    print(json.dumps(summary, ensure_ascii=True, separators=(",", ":")))
    return EXIT_SUCCESS


if __name__ == "__main__":
    raise SystemExit(main())
